language: node_js
node_js:
  - 12

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn --frozen-lockfile
  - lerna bootstrap

script:
  - yarn test
  - yarn lint
  - lerna run build
  - yarn coverage:collect
